image: r-base:latest

before_script:
  - echo "options(bitmapType='cairo')" >> ~/.Rprofile
  - apt-get update -qy
  - apt-get install -y cmake python gcc g++ git build-essential
  - curl -sL https://deb.nodesource.com/setup_4.x | bash -
  - apt-get install -y nodejs

stages:
  - build
  - test

build:
  stage: build
  script:
    - su - -c "R -e \"install.packages(c('shiny', 'rmarkdown'), repos='http://cran.rstudio.com')\""
    - npm install
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local
    - make
    - npm rebuild
    - ./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild
    - sudo ln -s /usr/local/shiny-server/bin/shiny-server /usr/bin/shiny-server
    - sudo useradd -r -m shiny
    - sudo mkdir -p /var/log/shiny-server
    - sudo mkdir -p /srv/shiny-server
    - sudo mkdir -p /var/lib/shiny-server
    - sudo chown shiny /var/log/shiny-server
    - sudo mkdir -p /etc/shiny-server
    - sudo wget https://raw.github.com/rstudio/shiny-server/master/config/upstart/shiny-server.conf -O /etc/init/shiny-server.conf
    - sudo start shiny-server
