image: node:4.4.3

cache:
  paths:
    - node_modules/

before_script:
  - echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
  - apt-get update -qq
  - apt-get install -qy cmake python gcc g++ git build-essential
  - apt-get install -qy r-base
  - echo "options(bitmapType='cairo')" >> ~/.Rprofile

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - /usr/local/shiny-server/bin/shiny-server
  script:
    - su - -c "R -e \"install.packages(c('shiny', 'rmarkdown'), repos='http://cran.rstudio.com')\""
    - npm install
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local
    - make
    - npm rebuild
    - ./ext/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild
    - ln -s /usr/local/shiny-server/bin/shiny-server /usr/bin/shiny-server
    - useradd -r -m shiny
    - mkdir -p /var/log/shiny-server
    - mkdir -p /srv/shiny-server
    - mkdir -p /var/lib/shiny-server
    - chown shiny /var/log/shiny-server
    - mkdir -p /etc/shiny-server
    - wget https://raw.github.com/rstudio/shiny-server/master/config/upstart/shiny-server.conf -O /etc/init/shiny-server.conf
    - start shiny-server
